version: '3.8'

services:
  sshtarpit:
    image: andreaskasper/ssh-tarpit:latest
    restart: always
    ports:
      - 22:22
    environment:
      - BIND_ADDRESS=0.0.0.0
      - BIND_PORT=22
      - VERBOSE=info
      - MAX_CLIENTS=4096
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s