# Example: SSH Tarpit with monitoring and log aggregation
# This setup includes Prometheus metrics export and centralized logging

version: '3.8'

services:
  ssh-tarpit:
    image: andreaskasper/ssh-tarpit:latest
    container_name: ssh-tarpit
    restart: unless-stopped
    
    ports:
      - "22:22"
    
    environment:
      - BIND_ADDRESS=0.0.0.0
      - BIND_PORT=22
      - VERBOSE=info
      - MAX_CLIENTS=4096
    
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
    
    # Send logs to Loki
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
        labels: "service=ssh-tarpit,environment=production"
    
    networks:
      - monitoring
    
    labels:
      - "prometheus.scrape=false"  # SSH tarpit doesn't expose metrics endpoint
      - "logging=true"

  # Log analyzer - extracts statistics from tarpit logs
  tarpit-stats:
    image: alpine:latest
    container_name: tarpit-stats
    restart: unless-stopped
    
    # This container periodically analyzes tarpit logs
    command: |
      sh -c '
        apk add --no-cache docker-cli jq;
        while true; do
          echo "=== SSH Tarpit Statistics (Last Hour) ===";
          docker logs --since 1h ssh-tarpit 2>&1 | grep -E "Connection|attempt" | wc -l | xargs echo "Total attempts:";
          docker logs --since 1h ssh-tarpit 2>&1 | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}" | sort | uniq -c | sort -rn | head -10;
          sleep 300;
        done
      '
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    depends_on:
      - ssh-tarpit
    
    networks:
      - monitoring

  # Optional: Export metrics to a file for Prometheus node_exporter textfile collector
  metrics-exporter:
    image: alpine:latest
    container_name: tarpit-metrics
    restart: unless-stopped
    
    command: |
      sh -c '
        apk add --no-cache docker-cli;
        mkdir -p /metrics;
        while true; do
          ATTEMPTS=$(docker logs --since 1h ssh-tarpit 2>&1 | grep -c "Connection" || echo 0);
          UNIQUE_IPS=$(docker logs --since 1h ssh-tarpit 2>&1 | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}" | sort -u | wc -l || echo 0);
          echo "# HELP ssh_tarpit_attempts_total Total SSH connection attempts" > /metrics/tarpit.prom;
          echo "# TYPE ssh_tarpit_attempts_total counter" >> /metrics/tarpit.prom;
          echo "ssh_tarpit_attempts_total $ATTEMPTS" >> /metrics/tarpit.prom;
          echo "# HELP ssh_tarpit_unique_ips Unique IP addresses attempting connections" >> /metrics/tarpit.prom;
          echo "# TYPE ssh_tarpit_unique_ips gauge" >> /metrics/tarpit.prom;
          echo "ssh_tarpit_unique_ips $UNIQUE_IPS" >> /metrics/tarpit.prom;
          sleep 60;
        done
      '
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./metrics:/metrics  # Mount this to node_exporter textfile directory
    
    depends_on:
      - ssh-tarpit

networks:
  monitoring:
    external: true

# To use with Prometheus node_exporter:
# 1. Mount ./metrics to your node_exporter textfile collector directory
# 2. node_exporter will automatically pick up the metrics
# 3. Add this to your prometheus.yml:
#    - job_name: 'node'
#      static_configs:
#        - targets: ['node-exporter:9100']